version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pikachu
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db
  webapp:
    image: nginx
    ports: "8080:80"

volumes:
  mongodb_data_container: